### ISSUE TITLE
Login Signup is not Working

### ISSUE THREAD

**Issue by rishabhborn2win** [brigadierpratap/UrlShortener#1]
<img width="1440" alt="Screenshot 2021-07-27 at 8 37 31 AM" src="https://user-images.githubusercontent.com/55771529/127089064-6c7974a7-34de-49ee-997b-29644f1a195a.png">

**Comment by brigadierpratap** [comment]
It's a dummy, 
Only the URL shortener is working.
There is no use authenticating a user since it's a free service.
If you wish to contribute, you're welcome. ;)
